# Install librairies

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import cv2

# Load datasets

In [31]:
# exercices_data_path = "../datasets/gym_exercise_dataset.csv"
# df = pd.read_csv(exercices_data_path)
# df

programs_path = "../datasets/programs_detailed_boostcamp_kaggle.csv"
df = pd.read_csv(programs_path)
df

# stretch_data_path = "../datasets/stretch_exercise_dataset.csv"
# df2 = pd.read_csv(stretch_data_path)
# df2

,Exercise Name,Equipment,Variation,Utility,Mechanics,Force,Preparation,Execution,Target_Muscles,Synergist_Muscles,Stabilizer_Muscles,Antagonist_Muscles,Dynamic_Stabilizer_Muscles,Main_muscle,Difficulty (1-5),Secondary Muscles,parent_id
0,Neck Flexion,Cable,No,Basic or Auxiliary,Isolated,Pull,Sit on bench facing away from middle pulley. P...,Move head away from pulley by bending neck for...,"Sternocleidomastoid,","None,","Rectus Abdominis, Obliques,",NaN,NaN,Neck,2,Sternocleidomastoid,NaN
1,Neck Flexion,Lever (plate loaded),No,Basic or Auxiliary,Isolated,Pull,Sit on seat in machine. Position padded lever ...,Move head forward by flexing neck until chin t...,"Sternocleidomastoid,","None,","Latissimus Dorsi, Deltoid, Posterior, Rhomboid...",NaN,NaN,Neck,2,Sternocleidomastoid,NaN
2,Lateral Neck Flexion,Lever (plate loaded),No,Auxiliary,Isolated,Pull,Sit on seat in machine with feet apart . Pos...,Move head down to side by laterally flexing ne...,"Sternocleidomastoid,","Splenius, Erector Spinae, Levator Scapulae, Tr...","Latissimus Dorsi, Pectoralis Major, Sternal, P...",NaN,NaN,Neck,2,"Sternocleidomastoid, Levator Scapulae",NaN
3,Neck Flexion,Lever (selectorized),No,Basic or Auxiliary,Isolated,Pull,Sit on seat in machine. Position padded lever ...,Move head forward by flexing neck until chin t...,"Sternocleidomastoid,","None,","Latissimus Dorsi, Deltoid, Posterior, Rhomboid...",NaN,NaN,Neck,2,Sternocleidomastoid,NaN
4,Lateral Neck Flexion,Lever (selectorized),No,Auxiliary,Isolated,Pull,Sit on seat in machine with feet apart. Positi...,Move head down to side by laterally flexing ne...,"Sternocleidomastoid,","Splenius, Erector Spinae, Levator Scapulae, Tr...","Latissimus Dorsi, Pectoralis Major, Sternal, P...",NaN,NaN,Neck,2,"Sternocleidomastoid, Levator Scapulae",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
612,Lying Reverse Calf Press,Sled,No,Basic or Auxiliary,Isolated,Pull,Position sled away from platform. Lie supine o...,Pull forefoot back toward body as far as possi...,"Tibialis Anterior,","None,","No significant stabilizers,",NaN,NaN,Calves,2,Tibialis Anterior,NaN
613,Seated Reverse Calf Press,Sled,No,Basic or Auxiliary,Isolated,Pull,Sit on seat and place feet very high on platfo...,Pull forefoot back toward body as far as possi...,"Tibialis Anterior,","None,","No significant stabilizers,",NaN,NaN,Calves,2,Tibialis Anterior,NaN
614,Reverse Calf Raise,Smith,No,Basic or Auxiliary,Isolated,Pull,Position bar upper chest height and place calf...,Pull forefoot of both feet up toward body as f...,"Tibialis Anterior,","None,","No significant stabilizers,",NaN,NaN,Calves,2,Tibialis Anterior,NaN
615,Reverse Calf Raise,Body Weight,No,Basic or Auxiliary,Isolated,Pull,Position heels on forward edge of calf block o...,Pull forefoot of both feet up toward body as f...,"Tibialis Anterior,","None,",NaN,NaN,NaN,Calves,2,Tibialis Anterior,NaN
616,Reverse Calf Raise: Single Leg,Body Weight,Yes,Auxiliary,Isolated,Pull,Position one heel on forward edge of platform....,Pull forefoot up toward body as far as possibl...,"Tibialis Anterior,","None,","Gluteus Medius, Gluteus Maximus, Quadratus Lum...",NaN,NaN,Calves,3,Tibialis Anterior,615.0

In [20]:
unique_exercices = df['Exercise Name'].nunique()

print(f"There are {unique_exercices} unique exercices in the dataset.")

There are 340 unique exercices in the dataset.

In [28]:
# Remove the rows with missing values in the 'Target muscle' feature
df = df.dropna(subset=['Target_Muscles'])
df

,Exercise Name,Equipment,Variation,Utility,Mechanics,Force,Preparation,Execution,Target_Muscles,Synergist_Muscles,Stabilizer_Muscles,Antagonist_Muscles,Dynamic_Stabilizer_Muscles,Main_muscle,Difficulty (1-5),Secondary Muscles,parent_id
7,Wall Front Neck Bridge,Body Weight,No,Basic or Auxiliary,Isolated,Push & Pull,Place small or folded cushioned mat on wall or...,Roll down onto forehead until nose touches mat...,"Sternocleidomastoid,","Splenius, Trapezius, Upper, Levator Scapulae, ...","Rectus Abdominis, Obliques, Quadriceps,","Erector Spinae,",NaN,Neck,3,"Sternocleidomastoid, Upper Trapezius",NaN
43,Front Raise,Suspended,No,Auxiliary,Isolated,Push,Grasp suspension handles and momentarily step ...,Raise arms upward overhead by flexing shoulder...,"Anterior Deltoid,","Pectoralis Major, Clavicular, Deltoid, Lateral...","Erector Spinae, Gluteus Maximus, Hamstrings, T...","Rectus Abdominis, Obliques,",NaN,Shoulder,2,"Anterior Deltoid, Serratus Anterior",NaN
59,Y Raise,Suspended,No,Auxiliary,Isolated,Pull,Grasp suspension handles and momentarily step ...,Raise arms upward and outward in shape of a Y ...,"Lateral Deltoid,","Deltoid, Anterior, Supraspinatus, Trapezius, L...","Erector Spinae, Gluteus Maximus, Hamstrings, T...","Rectus Abdominis, Obliques,",NaN,Shoulder,3,"Posterior Deltoid, Lower Trapezius",NaN
76,Rear Delt Inverted Row (high bar),Body Weight,No,Basic or Auxiliary,Compound,Pull,Stand facing horizontal bar positioned lower t...,"Lower body while keeping body straight, elbows...","Posterior Deltoid,","Infraspinatus, Teres Minor, Trapezius, Middle,...","Erector Spinae, Hamstrings, Gluteus Maximus, D...","Rectus Abdominis, Obliques,","Biceps Brachii,",Shoulder,4,"Posterior Deltoid, Latissimus Dorsi",NaN
77,Rear Delt Inverted Row (on hips),Body Weight,No,Basic or Auxiliary,Compound,Pull,Lay on back with belly under fixed horizontal ...,"Keeping hips on floor, low back straight, and ...","Posterior Deltoid,","Infraspinatus, Teres Minor, Trapezius, Middle,...","Erector Spinae,","Rectus Abdominis, Obliques,","Biceps Brachii,",Shoulder,4,"Posterior Deltoid, Latissimus Dorsi",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
556,Straight Hip Leg Curl (on ball),Body Weight,No,Basic or Auxiliary,Isolated,Pull,Position thighs prone on padding. Hook heels u...,"From upright position, lower body by straighte...","Hamstrings,","Gluteus Maximus, Adductor Magnus, Gastrocnemiu...","Erector Spinae,","Rectus Abdominis, Obliques, Tibialis Anterior,",NaN,Thighs,3,Hamstrings,NaN
557,Inverse Leg Curl,Self-assisted,No,Basic,Isolated,Pull,Place elevated platform in front of glute-hams...,Lower body with hips straight by slowly straig...,"Hamstrings,","Gastrocnemius, Gracilis, Sartorius, Popliteus,...","Gluteus Maximus, Adductor Magnus, Erector Spin...","Rectus Abdominis, Obliques, Rectus Femoris, Ti...",NaN,Thighs,3,Hamstrings,NaN
558,Leg Curl,Suspended,No,Basic or Auxiliary,Isolated,Pull,Sit on floor facing suspension trainer in low ...,Pull heels toward rear end by bending knees an...,"Hamstrings,","Gastrocnemius, Sartorius, Gracilis, Popliteus,","Gluteus Maximus, Erector Spinae,","Tibialis Anterior, Rectus Abdominis, Obliques,",NaN,Thighs,2,Hamstrings,NaN
559,Hanging Leg Curl,Suspended,No,Basic or Auxiliary,Isolated,Pull,Sit on floor facing suspension trainer in low ...,Pull heels toward rear end by bending knees an...,"Hamstrings,","Gastrocnemius, Sartorius, Gracilis, Popliteus,","Gluteus Maximus, Erector Spinae,","Tibialis Anterior, Rectus Abdominis, Obliques,",NaN,Thighs,3,Hamstrings,NaN
560,Straight Hip Leg Curl,Suspended,No,Basic or Auxiliary,Isolated,Pull,Sit on floor facing suspension trainer in low ...,"Bend knees, pulling heels toward rear end whil...","Hamstrings,","Gastrocnemius, Sartorius, Gracilis, Popliteus,","Gluteus Maximus, Erector Spinae,","Tibialis Anterior, Rectus Abdominis, Obliques,",NaN,Thighs,3,Hamstrings,NaN